language: go

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev libxslt-dev

os:
  - linux

compiler:
  - gcc
  - clang

go_import_path: github.com/wamuir/go-xslt

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - tip

script:
     - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
     - bash <(curl -s https://codecov.io/bash)
