language: go

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev libxslt-dev

os:
  - linux

compiler:
  - gcc
  - clang

go_import_path: github.com/wamuir/go-xslt

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master
